version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hope
      MYSQL_USER: meteor
      MYSQL_PASSWORD: Love1126
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: